version: "3.3"
services:
  postgresql:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./schema-test.sql:/docker-entrypoint-initdb.d/schema.sql
      - .postgresdata:/var/lib/postgresq
    restart: always
  redis:
    image: bitnami/redis
    container_name: redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_USERNAME=redis
    restart: always

